( slowa uzupelniajace slownik FORTH zdefiniowany w assemblerze )

FORTH DEFINITIONS DECIMAL

: IMMEDIATE LATEST 64 TOGGLE ;
: [COMPILE] -FIND 0= 0 ?ERROR DROP CFA , ; IMMEDIATE
: ;CODE ?CSP COMPILE (;CODE) [COMPILE] [ SMUDGE ; IMMEDIATE
: ?PAIRS - 19 ?ERROR ;
: ' -FIND 0= 0 ?ERROR DROP [COMPILE] LITERAL ; IMMEDIATE
: BACK HERE - , ;

: IF COMPILE 0BRANCH HERE 0 , 2 ; IMMEDIATE
: ENDIF ?COMP 2 ?PAIRS HERE OVER - SWAP ! ; IMMEDIATE
: THEN [COMPILE] ENDIF ; IMMEDIATE
: ELSE 2 ?PAIRS COMPILE BRANCH HERE 0 , SWAP 2 [COMPILE] ENDIF 2 ; IMMEDIATE

: BEGIN ?COMP HERE 1 ; IMMEDIATE
: AGAIN 1 ?PAIRS COMPILE BRANCH BACK ; IMMEDIATE
: REPEAT >R >R [COMPILE] AGAIN R> R> 2 - [COMPILE] ENDIF ; IMMEDIATE
: UNTIL 1 ?PAIRS COMPILE 0BRANCH BACK ; IMMEDIATE
: END [COMPILE] UNTIL ; IMMEDIATE
: WHILE [COMPILE] IF 2+ ; IMMEDIATE

: DO COMPILE (DO) HERE 3 ; IMMEDIATE
: LOOP 3 ?PAIRS COMPILE (LOOP) BACK ; IMMEDIATE
: +LOOP 3 ?PAIRS COMPILE (+LOOP) BACK ; IMMEDIATE

: ." 34 STATE @
  IF
    COMPILE (.") WORD HERE C@ 1+ ALLOT
  ELSE
    WORD HERE COUNT TYPE
  ENDIF
; IMMEDIATE

: VLIST [ C/L 1 - ] LITERAL OUT ! CONTEXT @ @
  BEGIN
    OUT @ C/L MOD OUT !
    DUP C@ 31 AND 1+ OUT @ + C/L >
    IF
      CR 0 OUT !
    ENDIF
    DUP ID. PFA LFA @
    DUP 0= ?TERMINAL OR
  UNTIL
  DROP
;

: FORGET
  CURRENT @ CONTEXT @ - 24 ?ERROR
  [COMPILE] ' DUP FENCE @ < 21 ?ERROR
  DUP NFA DP ! LFA @ CURRENT @ !
  RESIZE
;

( zapis aktualnego slownika )
: SAVE
  HERE FENCE !
  HERE [ 28 +ORIGIN ] LITERAL !
  HERE [ 30 +ORIGIN ] LITERAL !
  [ ' FORTH 4 + ] LITERAL @ [ 12 +ORIGIN ] LITERAL !
;

( definicje instrukcji wyboru )
: (BRKCASE) R> DROP R> DROP ;
: CASE COMPILE LIT HERE 0 , COMPILE >R COMPILE >R 4 ; IMMEDIATE
: OF 4 ?PAIRS 4 COMPILE R COMPILE = [COMPILE] IF 5 ; IMMEDIATE
: ENDOF 5 ?PAIRS COMPILE (BRKCASE) [COMPILE] ENDIF ; IMMEDIATE
: ENDCASE 4 ?PAIRS COMPILE (BRKCASE) HERE SWAP ! ; IMMEDIATE

SAVE
