$DEFINE OP_NOP          'b'0000
$DEFINE OP_EN           'b'0001
$DEFINE OP_DI           'b'0010

$DEFINE OP_FLOAT        'b'0000
$DEFINE OP_START        'b'0001
$DEFINE OP_FETCH        'b'0010

$DEFINE OP_RD_WORD      'b'0011
$DEFINE OP_RD_BYTE      'b'0100
$DEFINE OP_WR_WORD      'b'0101
$DEFINE OP_WR_BYTE      'b'0110
$DEFINE OP_R2R          'b'0111
$DEFINE OP_TEST_R       'b'1000
$DEFINE OP_TEST_M       'b'1001
$DEFINE OP_IMMED        'b'1010
$DEFINE OP_COND         'b'1011
$DEFINE OP_IOR          'b'1100
$DEFINE OP_IOW          'b'1101

$DEFINE OP_BIS          'b'1110

$DEFINE OP_RESET        'b'1111
